kind = "web"
previewPath = "/"
title = "BundlyPlus"
version = "1.0.0"
id = "artifacts/bundlyplus"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19772

[services.development]
run = "pnpm --filter @workspace/bundlyplus run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bundlyplus", "run", "build" ]
publicDir = "artifacts/bundlyplus/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19772"
BASE_PATH = "/"
